/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.ProjetoFinalDependenciasExternas;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.stream.Collectors;

import static br.com.ProjetoFinalDependenciasExternas.OperacaoArquivo.*;

public class App {

    public static void main(String[] args) {

        OrganizacaoBancaria organizacaoBancaria = new OrganizacaoBancaria();
        organizacaoBancaria.gerarExtrato();

    }



}
